node_js:
- "7.0"
- "6.0"
- "5.0"
- "4.0"
language: node_js
before_script:
  - npm install -g mocha
  - npm install -g istanbul
  - npm install -g gulp
script:
  - gulp babel
  - npm test
  - npm run cover